/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package get.the.sha.pkg1;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nasir Ayaz
 */
public class MainScreen extends javax.swing.JFrame {
	File file_keytool = null;
	File file_keystore = null;
        String alias = "";
        String password = "";
        String command = "";

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_keytool_path = new javax.swing.JLabel();
        btn_keytool = new javax.swing.JButton();
        label_keystore_path = new javax.swing.JLabel();
        btn_keystore = new javax.swing.JButton();
        et_alias = new javax.swing.JTextField();
        et_password = new javax.swing.JPasswordField();
        btn_proceed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tv_logs = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label_keytool_path.setText("Keytool Path");

        btn_keytool.setText("Browse");
        btn_keytool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keytoolMouseClicked(evt);
            }
        });

        label_keystore_path.setText("Keystore Path");

        btn_keystore.setText("Browse");
        btn_keystore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keystoreMouseClicked(evt);
            }
        });

        et_alias.setToolTipText("Enter Alias");

        btn_proceed.setText("GET");
        btn_proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proceedMouseClicked(evt);
            }
        });
        btn_proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proceedActionPerformed(evt);
            }
        });

        tv_logs.setEditable(false);
        tv_logs.setColumns(20);
        tv_logs.setRows(5);
        jScrollPane1.setViewportView(tv_logs);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("GET SHA-1 Key");

        jLabel1.setText("Enter Alias");

        jLabel2.setText("Enter Keystore Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_keytool_path, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_keytool))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(et_alias, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(et_password)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btn_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_keystore_path, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_keystore))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_keytool_path, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keytool))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_keystore)
                    .addComponent(label_keystore_path))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(et_alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        et_alias.getAccessibleContext().setAccessibleName("Enter Alias");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proceedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proceedActionPerformed

    private void btn_keytoolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keytoolMouseClicked
            JFileChooser j = new JFileChooser();
				j.setFileSelectionMode(JFileChooser.FILES_ONLY);
				Integer returnVal = j.showOpenDialog(btn_keytool);
				if (returnVal == JFileChooser.APPROVE_OPTION) {
                                    	file_keytool = j.getSelectedFile();
					label_keytool_path.setText(file_keytool.getAbsolutePath());
					pack();
				}
		
    }//GEN-LAST:event_btn_keytoolMouseClicked

    private void btn_keystoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keystoreMouseClicked
  JFileChooser j = new JFileChooser();
				j.setFileSelectionMode(JFileChooser.FILES_ONLY);
				Integer returnVal = j.showOpenDialog(btn_keystore);
				if (returnVal == JFileChooser.APPROVE_OPTION) {
                                    	file_keystore = j.getSelectedFile();
					label_keystore_path.setText(file_keystore.getAbsolutePath());
					pack();
				}    }//GEN-LAST:event_btn_keystoreMouseClicked

    private void btn_proceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proceedMouseClicked
           if(et_alias.getText().length() > 0){
               if(et_password.getPassword().length > 0){
                   alias = et_alias.getText().toString();
                   password = et_password.getPassword().toString();
                   
                   callterminal("\""+label_keytool_path.getText()+"\"" + " -list -v -keystore " +"\"" + label_keystore_path.getText()+ "\"" + " -alias " + alias + " -storepass " + String.valueOf(et_password.getPassword()));
               }else{
                 //show Error
                  showError("Invalid keystore password");
               }
           }else{
               showError("Invalid keystore alias");
           }
    }//GEN-LAST:event_btn_proceedMouseClicked

    
    
 private void  callterminal(String command){
       try {
      Reader rdr = null;
        Process proc = Runtime.getRuntime().exec(command);
        BufferedReader reader =  new BufferedReader(new InputStreamReader(proc.getInputStream()));
        String line = "";
        while((line = reader.readLine()) != null) {
            if(line.contains("SHA1:")){
            tv_logs.setText(line.trim());
            }else if(line.contains("Password verification failed")){
                  showError("Invalid Password");
            }else if(line.contains("Alias") && line.contains("does not exist")){
                  showError("Invalid  Alias");
            }else if(line.contains("Invalid keystore format")){
                  showError("Invalid keystore");
            }
            System.out.print(line + "\n");
        }
        proc.waitFor();   
         } catch (IOException ex) {
               showError("Invalid Path, Please check keytool path & keystore path");
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (InterruptedException ex) {
                           showError(ex.getMessage());
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    
 }
 
 private void showError(String text) {
		JOptionPane.showMessageDialog(this, text, "Error",
				JOptionPane.ERROR_MESSAGE);
	}

	private void showWarning(String text) {
		JOptionPane.showMessageDialog(this, text, "Warning",
				JOptionPane.WARNING_MESSAGE);
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keystore;
    private javax.swing.JButton btn_keytool;
    private javax.swing.JButton btn_proceed;
    private javax.swing.JTextField et_alias;
    private javax.swing.JPasswordField et_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_keystore_path;
    private javax.swing.JLabel label_keytool_path;
    private javax.swing.JTextArea tv_logs;
    // End of variables declaration//GEN-END:variables
}
